### ISSUE TITLE
Refresh token issues

### ISSUE THREAD

**Issue by suho** [anhkul11/Surveys#7]
- The Alamofire library supports `RequestRetrier`, I suggest you use it.
- With your current solution, when the token is expired, and at that time, the app calls 10 requests, then the network service will also call 10 refresh token requests. Could you tell me any solution to improve this?

**Comment by anhkul11** [comment]
Well, my origin solution is that whenever the API failed with the status code `401 (invalid access token)`, It would automated call another API to get the new one, using the refresh token as parameters.
If the second call failed too, then the first call would fail with its origin status code (401). On the other hand, It will retry with the new access token from the second API call.
This must be a bug in my projects. I will try to fix it. Also, the server doesn't specify which status code would be return if the client send invalid access token, so I will retry 3 times before assume that something's wrong with the access token and get a new one.

**Comment by suho** [comment]
![Screen Shot 2021-06-23 at 16 54 01](https://user-images.githubusercontent.com/19943832/123076790-a620d900-d443-11eb-9a8c-ce531e8f3180.png)

if the client sends an invalid access token, the status code is 401

**Comment by anhkul11** [comment]
@suho sorry I think I mis-uderstood your question. Here's my solution in #10 PR.
- I will retry `5 times` for each request to the server, using `RequestRetrier` as your suggestion.
- In order to avoid sending 10 refresh token requests to the server, I wait until there are `10 requests that failed` with the specific `invalid token` (status code: 401), then I call refresh token.
