### ISSUE TITLE
SnapKit Library

### ISSUE THREAD

**Issue by suho** [anhkul11/Surveys#8]
I see that you are using `SnapKit` to apply auto layout for custom views. Could you tell me any reason why you didn't apply it for screens (Login, SurveyList, Forgot...) instead of .storyboard?

**Comment by anhkul11** [comment]
I like to visualize everything on the storyboard/xib files. This way I can easily imagine how the view looks like, especially when the view contains complex subviews. And also I don't have to connect unnecessary outlets/constraints that will not be updated ever so that the code base will be cleaner.
`SnapKit` is very useful with its syntactic sugar, reliable functionality. This specific custom view is quite simple and doesn't have to associate with a xib file, so I use `SnapKit` to layout the view to make it faster and easy to read.
Also, I usually use `SnapKit` to create/edit constraints that don't appear on the initial state of the view.
